## Upload data

In [2]:
from google.colab import files
uploaded = files.upload()

Saving graded_assignment_1.csv to graded_assignment_1.csv

In [3]:
import pandas as pd
data = pd.read_csv('graded_assignment_1.csv')
data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,?,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,?,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,?,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

## Unknown values

In [10]:
data.apply(lambda x: x == '?').sum().sum()

1823

In [11]:
import numpy as np
data.replace('?',np.nan,inplace=True)
data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

## Shape of data

In [11]:
data.shape

(10000, 12)

## Value at Index

In [15]:
data.iloc[692,0]

'2009-11-16'

In [16]:
data.iloc[546,7]

3

## Unique values

In [7]:
data.groupby('Locality')['Locality'].count()

Locality
Bridgeport       1756
Fairfield        1195
Greenwich        1050
Norwalk           978
Stamford         1061
Waterbury        1539
West Hartford    1168
Name: Locality, dtype: int64

## Missing values

In [13]:
data.isna().sum()

Date                    0
Year                    0
Locality             1253
Estimated Value      1243
Sale Price              0
Property             1823
Residential             0
num_rooms               0
num_bathrooms           0
carpet_area          1229
property_tax_rate       0
Face                    0
dtype: int64

In [14]:
data.isna().sum().max()

1823

## Droppoing missing value records

In [25]:
updated_data = data.drop(data[data.isna().sum(axis=1) > 2].index)
updated_data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
4,2009-01-02,2009,Bridgeport,112351.0,210000.0,NaN,Detached House,3,2,1092.0,1.025953,East
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,2022-09-30,2022,Bridgeport,153660.0,322000.0,NaN,Detached House,3,3,917.0,1.003979,North
9996,2022-09-30,2022,Bridgeport,109820.0,340000.0,NaN,Duplex,4,4,1416.0,1.003979,North
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [26]:
updated_data = data.drop(data[data.isna().sum(axis=1) > 0].index)
updated_data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South
2,2009-01-02,2009,Waterbury,55720.0,140000.0,Single Family,Detached House,3,2,910.0,1.025953,South
3,2009-01-02,2009,Bridgeport,4775276.0,272900.0,Single Family,Detached House,3,1,971.0,1.025953,East
5,2009-01-02,2009,Greenwich,2868880.0,3300000.0,Single Family,Detached House,3,1,1039.0,1.025953,North
...,...,...,...,...,...,...,...,...,...,...,...,...
9986,2022-09-28,2022,Norwalk,305820.0,535000.0,Single Family,Detached House,3,2,1080.0,1.003979,West
9987,2022-09-28,2022,Norwalk,450510.0,677000.0,Single Family,Detached House,3,1,1000.0,1.003979,North
9993,2022-09-30,2022,West Hartford,121870.0,235000.0,Single Family,Detached House,3,2,1087.0,1.003979,South
9997,2022-09-30,2022,Waterbury,83210.0,170000.0,Single Family,Detached House,3,1,964.0,1.003979,South
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East